package localhost.hashing_without_knowing_how_to_hash.dto.ot;

import lombok.Getter;
import lombok.NoArgsConstructor;

import java.math.BigInteger;

/**
 * The private key / public key pair is generated by the sender of oblivious transfer
 * As the first step of the RSA oblivious transfer this RSA public key object is transferred to the receiver
 */
@NoArgsConstructor
public class PublicKeyRSADto {

    @Getter
    BigInteger n;
    @Getter
    BigInteger e;

    public PublicKeyRSADto(BigInteger n, BigInteger e){
        this.n=n;
        this.e=e;
    }

}
